### ISSUE TITLE
FEATURE add Template Debugging

### ISSUE THREAD

**Issue by korthjp17** [dynamic/recipe-silverstripe-base-site#18]
https://docs.silverstripe.org/en/4/developer_guides/debugging/template_debugging/

``` yml
---
Only:
  environment: 'dev'
---
SilverStripe\View\SSViewer:
  source_file_comments: true
```
